- hosts: terraform-ansible
  tasks:
    - name: Criando Arquivo index.html
      copy:
        dest: /home/ubuntu/index.html
        content: "<h1>Feito com terraform e Automatizado com ansible</h1>"

    - name: Criando servidor BusyBox
      shell: "nohup busybox httpd -f -p 8080 &"
